# Generated by Django 3.0.7 on 2020-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201013_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='placeholder_img_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
