# Generated by Django 3.0.7 on 2020-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_placeholder_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='placeholder_img_url',
        ),
        migrations.AddField(
            model_name='category',
            name='placeholder_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
