# Generated by Django 3.0.7 on 2020-11-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
