# Generated by Django 3.0.7 on 2020-11-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201115_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
